### ISSUE TITLE
Camel v1.2.0 outperforms v1.3.0 in puzzle

### ISSUE THREAD

**Issue by tissatussa** [bdmendes/camel#128]
Lately i gave this position to several engines. Camel v1.2.0 finds the solution Rd1 at depth 9 after 2 seconds, but v1.3.0 finds it only at depth 28 after 100 seconds !?

White to move.

![position_white-to-move-solution-Rd1](https://github.com/bdmendes/camel/assets/1109281/1e98ad89-7cbd-47e0-95d4-fbaacdbe07ff)

7Q/p2r4/kp6/4Bp2/P3b3/KP1q4/8/2R5 w - - 0 1

**Comment by bdmendes** [comment]
Hey @tissatussa, this is caused by late move reduction (#110). It causes the engine to calculate critical lines faster and reach higher depths, although skipping "quiet" moves and possibly performing a bit worse in puzzles like this. I have opened #129 with a more conservative depth reduction and will merge if the ELO reduction is insignificant.

**Comment by tissatussa** [comment]
OK.

Same with this position :

r1q2k1r/p3R1pp/2n5/1p3pB1/2pp4/2P5/3Q1PPP/4R1K1 w - - 0 21

![0_White-to-play-and-give-mate](https://github.com/bdmendes/camel/assets/1109281/7068b132-e219-4bdb-bd59-c06f90f9cbf6)

Camel v1.2.0 finds the solution Bh6 at depth 8 after 1 second, but v1.3.0 finds it only at depth 14 after 7 seconds ..

you write _..skipping "quiet" moves.._ but it this case, and also in the other position, the solution move (=clearly best) is a kind of "forcing move", so shouldn't be considered while performing "quiescence search" ?

anyhow, good luck improving the engine! I know it's hard to adjust parameters, keeping the overall performance high (or same), while being able to solve such puzzles, they might only point to a possible flaw in the code ..

**Comment by bdmendes** [comment]
Well, though it's desirable that quiesce search considers all forced moves, it's quite hard to consider the moves of these puzzles forced at least in the point of view of the engine (nothing is getting captured and threats may be ignored just as with any other move).
If you have the time, please check again with version 1.3.1. Your help is appreciated!

**Comment by tissatussa** [comment]
i compiled the newest v1.3.1 and now it finds Rd1 (first position) at depth 14 after 4 seconds, and Bh6 (second position) at depth 11 after 2 seconds : congrats !

how did you tune ? using self-play ? (version v1.3.0 against v1.3.1 in many (short??) games)

i wonder : can a "filter" be developed which selects such "unlikely" moves and put them on top the ordered-move-list ? I guess this is also about LMR ..

**Comment by bdmendes** [comment]
I rely on [fast-chess](https://github.com/Disservin/fast-chess) to play against the latest stable version automatically. I do 600 1/6+0.2 games (see https://github.com/bdmendes/camel/blob/master/gauntlet.sh). In this case, I tuned it right away (#129) because I knew it would improve this scenario.

Regarding move orders, I would only try to innovate in the regular search, not quiesce. Quiesce needs to be as simple as possible. Do you have any specific move heuristic idea you'd want to try? Feel free to fork this and do your own experiments, or I can try it in a few weeks. I'll be a bit busy in the upcoming days.

**Comment by tissatussa** [comment]
> ..Quiesce needs to be as simple as possible..

but are Rd1 and Bh6 ever considered ? And their following capture sequence ? I think their variations lead to "obvious" continuations, most of which might instanly be rejected by the eval logic ? Anyhow, i'm not a programmer of any engine yet, i'm only imagining the workings of (simple) chess engines and test them by playing against eachother, feeding them with puzzles and certain positions, to see how they act .. in many cases it seems the "horizon effect" (not reaching high enough depth) is a main bottleneck in tactical positions like the ones i gave.

> ..Do you have any specific move heuristic idea you'd want to try? Feel free to fork this and do your own experiments..

i don't do Rust ..

**Comment by bdmendes** [comment]
> i don't do Rust ..

You should try it someday, it's a bit difficult to get into but a joy to work with afterwards!

> but are Rd1 and Bh6 ever considered ? And their following capture sequence ? I think their variations lead to "obvious" continuations, most of which might instantly be rejected by the eval logic ? Anyhow, i'm not a programmer of any engine yet, i'm only imagining the workings of (simple) chess engines and test them by playing against eachother, feeding them with puzzles and certain positions, to see how they act .. in many cases it seems the "horizon effect" (not reaching high enough depth) is a main bottleneck in tactical positions like the ones i gave.

They aren't in quiesce; quiesce only strictly generates capture moves to "resolve" ambiguity at depth == 0. If you try to add more logic on quiesce and analyse more moves that might lead to combinations, there would be an explosion of nodes with a negative impact on all depths. The tuning should be done on the regular search, I believe.
